default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tsubuyaki_development

test:
  <<: *default
  database: tsubuyaki_test

production:
  <<: *default
  database: tsubuyaki_production
  username: tsubuyaki
  password: <%= ENV['TSUBUYAKI_DATABASE_PASSWORD'] %>
